/**
 * Unit tests for GoWM Type Generator (Phase 4.4)
 */
const { generateTypes, mapType, toPascalCase } = require('../../src/tools/type-generator');

describe('Type Generator (Phase 4.4)', () => {

    describe('toPascalCase()', () => {
        test('should convert kebab-case', () => {
            expect(toPascalCase('math-wasm')).toBe('MathWasm');
        });

        test('should convert snake_case', () => {
            expect(toPascalCase('my_module')).toBe('MyModule');
        });

        test('should handle single word', () => {
            expect(toPascalCase('math')).toBe('Math');
        });

        test('should handle already PascalCase', () => {
            expect(toPascalCase('MathWasm')).toBe('MathWasm');
        });
    });

    describe('mapType()', () => {
        test('should map standard JS types', () => {
            expect(mapType('string')).toBe('string');
            expect(mapType('number')).toBe('number');
            expect(mapType('boolean')).toBe('boolean');
            expect(mapType('object')).toBe('Record<string, any>');
            expect(mapType('any')).toBe('any');
        });

        test('should map Go-like types', () => {
            expect(mapType('int')).toBe('number');
            expect(mapType('float')).toBe('number');
            expect(mapType('float64')).toBe('number');
        });

        test('should return any for unknown types', () => {
            expect(mapType('unknown-type')).toBe('any');
            expect(mapType(null)).toBe('any');
            expect(mapType(undefined)).toBe('any');
        });
    });

    describe('generateTypes()', () => {
        const mathMetadata = {
            name: 'math-wasm',
            version: '0.2.0',
            description: 'Mathematical operations',
            functions: [
                {
                    name: 'add',
                    description: 'Add two numbers',
                    parameters: [
                        { name: 'a', type: 'number' },
                        { name: 'b', type: 'number' }
                    ],
                    returnType: 'number'
                },
                {
                    name: 'factorial',
                    description: 'Calculate factorial',
                    parameters: [
                        { name: 'n', type: 'number' }
                    ],
                    returnType: 'number'
                },
                {
                    name: 'mean',
                    description: 'Calculate mean',
                    parameters: [
                        { name: '...numbers', type: 'number' }
                    ],
                    returnType: 'number'
                },
                {
                    name: 'round',
                    description: 'Round a number',
                    parameters: [
                        { name: 'x', type: 'number' },
                        { name: 'precision', type: 'number', optional: true }
                    ],
                    returnType: 'number'
                },
                { name: 'getAvailableFunctions', returnType: 'string' },
                { name: 'setSilentMode', returnType: 'void' }
            ]
        };

        test('should generate valid TypeScript interface', () => {
            const result = generateTypes(mathMetadata);

            expect(result).toContain('export interface MathWasmBridge extends WasmBridge');
            expect(result).toContain("import { WasmBridge, LoadOptions } from 'gowm'");
            expect(result).toContain("call(func: 'add', a: number, b: number): number;");
            expect(result).toContain("call(func: 'factorial', n: number): number;");
        });

        test('should handle variadic parameters', () => {
            const result = generateTypes(mathMetadata);
            expect(result).toContain("call(func: 'mean', ...numbers: number[]): number;");
        });

        test('should handle optional parameters', () => {
            const result = generateTypes(mathMetadata);
            expect(result).toContain("call(func: 'round', x: number, precision?: number): number;");
        });

        test('should skip system functions', () => {
            const result = generateTypes(mathMetadata);
            expect(result).not.toContain("'getAvailableFunctions'");
            expect(result).not.toContain("'setSilentMode'");
        });

        test('should include header comments', () => {
            const result = generateTypes(mathMetadata);
            expect(result).toContain('Auto-generated by GoWM Type Generator');
            expect(result).toContain('math-wasm@0.2.0');
        });

        test('should generate module options interface', () => {
            const result = generateTypes(mathMetadata);
            expect(result).toContain('export interface MathWasmOptions extends LoadOptions');
        });

        test('should use custom interface name', () => {
            const result = generateTypes(mathMetadata, { interfaceName: 'MathBridge' });
            expect(result).toContain('export interface MathBridge extends WasmBridge');
        });

        test('should include JSDoc by default', () => {
            const result = generateTypes(mathMetadata);
            expect(result).toContain('/** Add two numbers */');
        });

        test('should exclude JSDoc when option is false', () => {
            const result = generateTypes(mathMetadata, { includeJSDoc: false });
            expect(result).not.toContain('/** Add two numbers */');
        });

        test('should throw for invalid metadata', () => {
            expect(() => generateTypes(null)).toThrow('Invalid metadata');
            expect(() => generateTypes({})).toThrow('missing "name"');
        });

        test('should handle metadata with no functions', () => {
            const result = generateTypes({ name: 'empty-wasm', version: '0.1.0' });
            expect(result).toContain('export interface EmptyWasmBridge extends WasmBridge');
        });
    });
});
